### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by AlexWayfer**
*   Actualize Ruby versions for Travis CI 
    Ruby 2.2 and 2.3 and below are not supported anymore.
*   Don't require system (bundled) gems
*   Use `require_relative` instead of `require`
    Don't require files from installed gem.
*   Update dependencies, improve versions locks
    Alpha-versions (`0.x.y`) should be locked on `y` (patch version),
    because of `x` (minor version) update may brings breaking changes.
*   Fix tests for Users and Users Stats
    Some profiles become private (closed), some was renamed.
*   Replace deprecated `Fixnum` with `Integer`
    Remove Ruby warnings.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
@bhaberer, I've made more updates and improvements! Are you interested in this gem? I can help to maintain, if you'd like.

**Comment by AlexWayfer** [comment]
@bhaberer thank you, here is just a friendly reminder!

**Comment by AlexWayfer** [comment]
@bhaberer and another one…

**Comment by AlexWayfer** [comment]
I have now failed specs, but I don't know how to fix them:

```
Failures:

  1) Steam::Player.recently_played_games returns the list of games
     Failure/Error: expect(p(result)).to have_key('games')
       expected #has_key?("games") to return true, got false
     # ./spec/steam/player_spec.rb:34:in `block (3 levels) in <top (required)>'

  2) Steam::Player.recently_played_games returns the recent playtime for games
     Failure/Error: expect(result['games'].first).to have_key('playtime_2weeks')
     
     NoMethodError:
       undefined method `first' for nil:NilClass
     # ./spec/steam/player_spec.rb:38:in `block (3 levels) in <top (required)>'

  3) Steam::Player.recently_played_games returns the full playtime for games
     Failure/Error: expect(result['games'].first).to have_key('playtime_forever')
     
     NoMethodError:
       undefined method `first' for nil:NilClass
     # ./spec/steam/player_spec.rb:42:in `block (3 levels) in <top (required)>'

Finished in 1 minute 51.05 seconds (files took 0.12711 seconds to load)
78 examples, 3 failures

Failed examples:

rspec ./spec/steam/player_spec.rb:33 # Steam::Player.recently_played_games returns the list of games
rspec ./spec/steam/player_spec.rb:37 # Steam::Player.recently_played_games returns the recent playtime for games
rspec ./spec/steam/player_spec.rb:41 # Steam::Player.recently_played_games returns the full playtime for games
```

In the future, we will need for cassettes, like [VCR](https://relishapp.com/vcr/vcr/docs).

**Comment by AlexWayfer** [comment]
@bhaberer yet another friendly reminder.

**Comment by AlexWayfer** [comment]
@bhaberer when this "soon" will be? 😰

**Comment by bhaberer** [comment]
Sorry I'm the worst, I'll look at this now 😅

**Comment by AlexWayfer** [comment]
> LGTM, I'll merge and package a new ver soon

Thank you!

**Pull request merged**
